jQuery(document).ready(function(){
    $('#fadein_apple').css("opacity","1");
    $('#fadein_icon').css("opacity","1");
    $('#slide_h1').css({"left":"0","opacity":"1"});
    $('#slide_p1').css({"left":"0","opacity":"1"});
    $('#slide_h2').css({"left":"0","opacity":"1"});
    $('#slide_p2').css({"left":"0","opacity":"1"});
    $('#breakline1').css({"left":"0","opacity":"1"});
    $('#breakline2').css({"left":"0","opacity":"1"});
    $('#breakline3').css({"left":"0","opacity":"1"});
});